import { NextRequest, NextResponse } from 'next/server';

export async function GET(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  // In a real app, this would fetch from database
  // For now, return a downloadable certificate format
  const { id } = await params;
  
  const certificate = {
    id,
    title: "VerifyAgent Verification Certificate",
    timestamp: new Date().toISOString(),
    message: "This certificate validates that the submitted work has been analyzed by VerifyAgent AI Oracle and meets the specified verification criteria.",
    signature: `Verified by VerifyAgent Oracle System`,
    hash: `0x${Math.random().toString(16).substring(2, 18)}`
  };

  const certificateText = `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                              VERIFYAGENT VERIFICATION CERTIFICATE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Certificate ID: ${certificate.id}
Issued: ${certificate.timestamp}

This certificate validates that the submitted work has been analyzed by the VerifyAgent 
AI Oracle system and meets the specified verification criteria.

Status: ✓ VERIFIED
Oracle: VerifyAgent AI System
Blockchain: Base L2 (simulated)
Signature: ${certificate.signature}
Hash: ${certificate.hash}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This certificate can be independently verified at: https://verifyagent.vercel.app/verify/${certificate.id}

Generated by VerifyAgent Oracle System - Synthesis Hackathon 2026
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`;

  return new NextResponse(certificateText, {
    headers: {
      'Content-Type': 'text/plain',
      'Content-Disposition': `attachment; filename="verification-certificate-${params.id}.txt"`
    }
  });
}